import React from 'react'

export default function Coins() {
  return (
    <div>
      <svg
        width="160"
        height="40"
        viewBox="0 0 160 40"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <circle
          cx="140"
          cy="20"
          r="19"
          fill="#C0C7C0"
          stroke="#389D3C"
          strokeWidth="2"
        />
        <circle
          cx="116"
          cy="20"
          r="19"
          fill="#C0C7C0"
          stroke="#389D3C"
          strokeWidth="2"
        />
        <circle
          cx="92"
          cy="20"
          r="19"
          fill="#C0C7C0"
          stroke="#389D3C"
          strokeWidth="2"
        />
        <circle
          cx="68"
          cy="20"
          r="19"
          fill="#C0C7C0"
          stroke="#389D3C"
          strokeWidth="2"
        />
        <circle
          cx="44"
          cy="20"
          r="19"
          fill="#C0C7C0"
          stroke="#389D3C"
          strokeWidth="2"
        />
        <circle
          cx="20"
          cy="20"
          r="19"
          fill="#C0C7C0"
          stroke="#389D3C"
          strokeWidth="2"
        />
      </svg>
    </div>
  )
}
